### ISSUE TITLE
Error during convertion from Evernote *.enex file to Notesnook zip-file

### ISSUE THREAD

**Issue by Dr4co** [streetwriters/notesnook-importer#107] opened 2023-12-12 11:33 UTC
Unable to do import due to error message:
`1. Invalid string. Lenght must be a multiple of 4`

My actual file contains 562 notes in that specific Notebook.

![Evernote to Notesnook](https://github.com/streetwriters/notesnook-importer/assets/3043372/551e7f61-1633-47ef-a221-6e1eab5fa430)

**Comment by thecodrr** [comment] 2023-12-13 08:42
Can you share the 324th note in that ENEX file somehow? That's where the issue is.

**Comment by Dr4co** [comment] 2023-12-18 21:54
Sure thing! I was able to identify a divided *.enex file that had the same issue, which only contained 63 notes, but results in the same error message after 15 notes. I have attached the note-file in a *.zip-file :)

[inköp - intressant.4.zip](https://github.com/streetwriters/notesnook-importer/files/13708884/inkop.-.intressant.4.zip)
![Evernote to Notesnook 63 notes, found 15](https://github.com/streetwriters/notesnook-importer/assets/3043372/61f1e94b-ac60-453c-8bac-eeaefe8ceaf4)

**Comment by thecodrr** [comment] 2023-12-19 04:15
@Dr4co fixed in v2.1.4! Thanks for the sample!

**Closed by thecodrr** 2023-12-19 04:15 UTC
